CREATE TABLE "mytable" (
  "CREATE OR REPLACE TABLE `rakamin-kf-analytics-470212.kimia_farma.tabel_analisa` AS" text NULL
);

INSERT INTO "mytable" ("CREATE OR REPLACE TABLE `rakamin-kf-analytics-470212.kimia_farma.tabel_analisa` AS")
VALUES
('SELECT'),
('ft.transaction_id'),
('ft.date'),
('ft.branch_id'),
('kc.branch_name'),
('kc.kota'),
('kc.provinsi'),
('kc.rating AS rating_cabang'),
('ft.customer_name'),
('ft.product_id'),
('p.product_name'),
('ft.price AS actual_price'),
('ft.discount_percentage'),
(NULL),
('-- Hitung persentase gross laba'),
('CASE'),
('WHEN ft.price <= 50000 THEN 0.10'),
('WHEN ft.price > 50000 AND ft.price <= 100000 THEN 0.15'),
('WHEN ft.price > 100000 AND ft.price <= 300000 THEN 0.20'),
('WHEN ft.price > 300000 AND ft.price <= 500000 THEN 0.25'),
('WHEN ft.price > 500000 THEN 0.30'),
('END AS persentase_gross_laba'),
(NULL),
('-- Nett sales (harga setelah diskon)'),
('(ft.price * (1 - ft.discount_percentage/100)) AS nett_sales'),
(NULL),
('-- Nett profit (nett sales * persentase laba)'),
('(ft.price * (1 - ft.discount_percentage/100)) *'),
('CASE'),
('WHEN ft.price <= 50000 THEN 0.10'),
('WHEN ft.price > 50000 AND ft.price <= 100000 THEN 0.15'),
('WHEN ft.price > 100000 AND ft.price <= 300000 THEN 0.20'),
('WHEN ft.price > 300000 AND ft.price <= 500000 THEN 0.25'),
('WHEN ft.price > 500000 THEN 0.30'),
('END AS nett_profit'),
(NULL),
('ft.rating AS rating_transaksi'),
(NULL),
('FROM `rakamin-kf-analytics-470212.kimia_farma.kf_final_transaction` ft'),
('LEFT JOIN `rakamin-kf-analytics-470212.kimia_farma.kf_product` p'),
('ON ft.product_id = p.product_id'),
('LEFT JOIN `rakamin-kf-analytics-470212.kimia_farma.kf_kantor_cabang` kc'),
('ON ft.branch_id = kc.branch_id;');
